const $ = (selector) => document.querySelector(selector);
const state = { providers: [], models: [], pricing: [], capabilities: [], api: [], categories: {}, recommendations: [], selectedRecommendation: 'strongest' };

async function loadRegistry() {
  const files = ['providers', 'models', 'pricing', 'capabilities', 'api', 'categories', 'recommendations'];
  const values = await Promise.all(files.map((file) => fetch(`./data/${file}.json`).then((response) => { if (!response.ok) throw new Error(`${file}.json load failed`); return response.json(); })));
  [state.providers, state.models, state.pricing, state.capabilities, state.api, state.categories, state.recommendations] = values;
  renderStats(); renderProviders(); renderMatcher(); renderGlossary(); renderRegistryNotice();
}

const byId = (items, key, value) => items.find((item) => item[key] === value);
const unknown = (value) => value === undefined || value === null || value === '' ? 'unknown' : value;
function providerFor(model) { return byId(state.providers, 'id', model.provider_id) || {}; }
function pricingFor(model) { return byId(state.pricing, 'model_id', model.id) || {}; }
function capabilityFor(model) { return byId(state.capabilities, 'model_id', model.id) || {}; }
function apiFor(model) { return byId(state.api, 'provider', model.provider_id) || {}; }

function renderStats() { $('#provider-count').textContent = state.providers.length; $('#series-count').textContent = new Set(state.models.map((model) => model.model_family)).size; $('#variant-count').textContent = state.models.length; }
function providerCard(provider) { const models = state.models.filter((model) => model.provider_id === provider.id); return `<article class="provider-card"><div class="provider-card-head"><span class="provider-logo ${provider.country === 'US' ? 'blue' : 'red'}">${provider.name.slice(0, 1)}</span><span class="region">${provider.country}</span><span class="open-source">${models.length} 个模型</span></div><h3>${provider.name_cn}</h3><p>${provider.description_cn}</p><div class="series-list"><strong>旗下模型</strong>${models.map(modelRow).join('')}</div></article>`; }
function modelRow(model) { const price = pricingFor(model); return `<button class="series-row" data-variant="${model.id}"><span><b>${model.display_name_cn}</b><small>${model.model_family} · ${model.model_type.join(' / ')}</small></span><i>${unknown(price.input_price)} ${price.currency || ''} / ${price.unit || 'unknown'} ↗</i></button>`; }
function renderProviders(filter = 'all') { $('#provider-grid').innerHTML = state.providers.filter((provider) => filter === 'all' || provider.country === filter || (filter === '开源' && state.models.some((model) => model.provider_id === provider.id && model.model_type.includes('Open Weight')))).map(providerCard).join(''); }

function renderMatcher() { const tasks = state.categories.tasks || []; const icons = ['✦','⌘','⚙','◉','⌂','♧','↗']; $('#task-options').innerHTML = tasks.map((task, index) => `<button class="task-option ${index === 0 ? 'selected' : ''}" data-task="${task.id}"><span>${icons[index] || '◎'}</span><b>${task.name_cn}</b><small>${task.description_cn}</small></button>`).join(''); state.selectedTask = tasks[0]?.id || ''; state.selectedRecommendation = ''; renderRecommendation(); }
function modelsForRecommendation(item) { return (item.model_ids || []).map((id) => byId(state.models, 'id', id)).filter(Boolean); }
function renderRecommendation() { const task = (state.categories.tasks || []).find((item) => item.id === state.selectedTask); const strategy = byId(state.recommendations, 'id', state.selectedRecommendation); let models = strategy ? modelsForRecommendation(strategy) : []; let title = strategy?.label || task?.name_cn || '任务推荐'; let reason = strategy?.reason || task?.description_cn || '根据模型类型匹配。'; if (task && !strategy) { models = state.models.filter((model) => model.model_type.some((type) => task.model_types.includes(type))).slice(0, 3); reason = '根据任务所需模型分类筛选；能力与价格为 unknown 的字段不参与事实判断。'; } const rows = models.length ? models.map((model, index) => `<button class="result-row" data-variant="${model.id}"><span class="rank">0${index + 1}</span><span class="result-main"><b>${model.display_name_cn}</b><small>${providerFor(model).name_cn} · ${model.model_family}</small></span><span class="result-reason">${model.description_cn}</span><span class="arrow">→</span></button>`).join('') : `<div class="unknown-result"><b>暂不输出排序</b><p>${reason}</p></div>`; $('#recommendation').innerHTML = `<div class="result-head"><div><span class="eyebrow">REGISTRY RECOMMENDATION</span><h3>${title}</h3></div><span class="match-badge">${models.length ? 'CANDIDATES' : 'UNKNOWN'}</span></div>${rows}<p class="disclaimer">${reason}</p>`; }
function renderGlossary() { const items = state.categories.name_suffixes || []; $('#glossary-grid').innerHTML = items.map((item) => `<article class="glossary-card"><span>✦</span><div><h3>${item.term}</h3><b>${item.name_cn}</b><p>${item.description_cn}</p></div></article>`).join(''); }
function capabilityChip(label, value) { return `<span class="${value === true ? 'on' : ''}">${label}: ${value === true ? 'yes' : unknown(value)}</span>`; }
function showVariant(id) { const model = byId(state.models, 'id', id); if (!model) return; const provider = providerFor(model); const price = pricingFor(model); const capability = capabilityFor(model); const api = apiFor(model); $('#detail-content').innerHTML = `<div class="detail-title"><span class="provider-logo ${provider.country === 'US' ? 'blue' : 'red'}">${provider.name.slice(0, 1)}</span><div><span class="eyebrow">${provider.name_cn} · ${model.model_family}</span><h2>${model.display_name_cn}</h2><p>${model.model_name} · ${model.model_type.join(' / ')} · Model ID: ${model.model_id}</p></div></div><div class="positioning"><b>${model.description_cn}</b><br>${model.usage_example_cn}</div><div class="capabilities">${capabilityChip('Reasoning',capability.reasoning)}${capabilityChip('Coding',capability.coding)}${capabilityChip('Vision',capability.vision)}${capabilityChip('Audio',capability.audio)}${capabilityChip('Context',capability.context_length)}${capabilityChip('Streaming',capability.streaming)}${capabilityChip('Function Calling',capability.function_calling)}${capabilityChip('JSON Mode',capability.json_mode)}${capabilityChip('Tool Calling',capability.tool_calling)}</div><div class="detail-grid"><div><h4>推荐用途</h4><ul class="detail-list">${model.best_for.map((item) => `<li>✓ ${item}</li>`).join('')} </ul><h4>避免用途</h4><p class="muted">${model.avoid_for.join(' · ')}</p><h4>价格</h4><p class="muted">输入：${unknown(price.input_price)} ${price.currency || ''} · 输出：${unknown(price.output_price)} ${price.currency || ''}<br>缓存：${unknown(price.cache_price)} · 单位：${price.unit || 'unknown'}<br>生效时间：${price.effective_from || 'unknown'}</p></div><div class="compare-box"><h4>API 参数</h4><div class="api-fact"><b>Base URL</b><code>${api.base_url || 'unknown'}</code></div><div class="api-fact"><b>API Format</b><code>${api.api_format || 'unknown'}</code></div><div class="api-fact"><b>Compatible with OpenAI</b><code>${unknown(api.compatible_with_openai)}</code></div><div class="api-fact"><b>Authentication</b><code>${api.authentication || 'unknown'}</code></div><h4>来源状态</h4><p class="muted">来源：${model.source || 'unknown'}<br>最后核验：${model.last_verified || 'unknown'}</p></div></div>`; $('#modal').classList.remove('hidden'); }
function renderRegistryNotice() { const node = document.createElement('p'); node.className = 'registry-notice'; node.textContent = '唯一 Registry 数据源：未核验字段显示为 unknown。价格和能力数据请以厂商官方文档为准。'; document.querySelector('#providers').prepend(node); }

document.addEventListener('click', (event) => { const filter = event.target.closest('[data-provider-filter]'); if (filter) { document.querySelectorAll('[data-provider-filter]').forEach((button) => button.classList.remove('active')); filter.classList.add('active'); const value = { '美国': 'US', '中国': 'CN', '开源': 'open' }[filter.dataset.providerFilter] || 'all'; $('#provider-grid').innerHTML = state.providers.filter((provider) => value === 'all' || provider.country === value || (value === 'open' && state.models.some((model) => model.provider_id === provider.id && model.model_type.includes('Open Weight')))).map(providerCard).join(''); } const task = event.target.closest('[data-task]'); if (task) { document.querySelectorAll('[data-task]').forEach((button) => button.classList.remove('selected')); task.classList.add('selected'); state.selectedTask = task.dataset.task; state.selectedRecommendation = ''; renderRecommendation(); } const choice = event.target.closest('[data-recommendation]'); if (choice) { document.querySelectorAll('[data-recommendation]').forEach((button) => button.classList.remove('selected')); choice.classList.add('selected'); state.selectedRecommendation = choice.dataset.recommendation; state.selectedTask = ''; renderRecommendation(); } const variant = event.target.closest('[data-variant]'); if (variant) showVariant(variant.dataset.variant); });
$('#modal-close').addEventListener('click', () => $('#modal').classList.add('hidden')); $('#modal').addEventListener('click', (event) => { if (event.target.id === 'modal') $('#modal').classList.add('hidden'); }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') $('#modal').classList.add('hidden'); });
loadRegistry().catch((error) => { console.error(error); document.body.insertAdjacentHTML('beforeend', '<p class="load-error">请通过本地静态服务器启动，以加载 Registry JSON 数据。</p>'); });
