const $ = (selector) => document.querySelector(selector);
const state = { providers: [], models: [], pricing: [], capabilities: [], endpoints: [], recommendations: [], selectedRecommendation: 'strongest' };

async function loadRegistry() {
  const files = ['providers', 'models', 'pricing', 'capabilities', 'api_endpoints', 'recommendations'];
  const values = await Promise.all(files.map((file) => fetch(`./data/${file}.json`).then((response) => { if (!response.ok) throw new Error(`${file}.json load failed`); return response.json(); })));
  [state.providers, state.models, state.pricing, state.capabilities, state.endpoints, state.recommendations] = values;
  renderStats(); renderProviders(); renderMatcher(); renderGlossary(); renderRegistryNotice();
}

const byId = (items, key, value) => items.find((item) => item[key] === value);
function providerFor(model) { return byId(state.providers, 'id', model.providerId); }
function pricingFor(model) { return byId(state.pricing, 'modelId', model.id) || {}; }
function capabilityFor(model) { return byId(state.capabilities, 'modelId', model.id) || {}; }
function endpointFor(model) { return byId(state.endpoints, 'providerId', model.providerId) || {}; }
function unknown(value) { return value === undefined || value === null || value === '' ? 'unknown' : value; }

function renderStats() { $('#provider-count').textContent = state.providers.length; $('#series-count').textContent = new Set(state.models.map((model) => model.modelFamily)).size; $('#variant-count').textContent = state.models.length; }
function providerCard(provider) {
  const models = state.models.filter((model) => model.providerId === provider.id);
  return `<article class="provider-card"><div class="provider-card-head"><span class="provider-logo ${provider.regions.includes('US') ? 'blue' : 'red'}">${provider.name.slice(0, 1)}</span><span class="region">${provider.regions.join(' / ')}</span><span class="open-source">${provider.focus.includes('open_weights') ? '开放权重 / 开源生态' : '商业厂商'}</span></div><h3>${provider.name}</h3><p>${provider.focus.join(' · ')}</p><div class="series-list"><strong>模型 / 系列</strong>${models.map(modelRow).join('')}</div></article>`;
}
function modelRow(model) { const price = pricingFor(model); return `<button class="series-row" data-variant="${model.id}"><span><b>${model.modelName}</b><small>${model.modelFamily} · ${model.modelType.join(' / ')}</small></span><i>${unknown(price.inputPrice)} ${price.currency || ''} / ${price.unit || 'unknown'} ↗</i></button>`; }
function renderProviders() { $('#provider-grid').innerHTML = state.providers.map(providerCard).join(''); }

function renderMatcher() { const options = state.recommendations.map((item, index) => `<button class="task-option ${index === 0 ? 'selected' : ''}" data-recommendation="${item.id}"><span>${['✦','↗','♧','⚙','⌘'][index] || '◎'}</span><b>${item.label}</b><small>${item.reason}</small></button>`).join(''); $('#task-options').innerHTML = options; renderRecommendation(); }
function renderRecommendation() { const recommendation = byId(state.recommendations, 'id', state.selectedRecommendation); if (!recommendation) return; const models = recommendation.modelIds.map((id) => byId(state.models, 'id', id)).filter(Boolean); const rows = models.length ? models.map((model, index) => `<button class="result-row" data-variant="${model.id}"><span class="rank">0${index + 1}</span><span class="result-main"><b>${model.modelName}</b><small>${providerFor(model).name} · ${model.modelFamily}</small></span><span class="result-reason">${recommendation.reason}</span><span class="arrow">→</span></button>`).join('') : `<div class="unknown-result"><b>暂不输出排序</b><p>${recommendation.reason}</p></div>`; $('#recommendation').innerHTML = `<div class="result-head"><div><span class="eyebrow">REGISTRY RECOMMENDATION</span><h3>${recommendation.label}</h3></div><span class="match-badge">${models.length ? 'CANDIDATES' : 'UNKNOWN'}</span></div>${rows}<p class="disclaimer">推荐只使用 Registry 中已登记的模型；unknown 字段不会被当成已知事实。</p>`; }

function renderGlossary() { const items = [{term:'Mini',label:'小型版本',detail:'常用于速度 / 成本取向；具体能力差异需查官方资料。',icon:'↘'},{term:'Pro',label:'专业增强版',detail:'通常代表产品线定位，不能直接等同于能力排名。',icon:'✦'},{term:'Flash',label:'高速版本',detail:'通常用于快速响应场景；速度与价格需核验。',icon:'ϟ'},{term:'Reasoning',label:'推理增强',detail:'通常用于数学、规划和复杂问题。',icon:'◎'},{term:'Vision',label:'视觉模型',detail:'通常表示图像理解或视觉输入能力。',icon:'◉'}]; $('#glossary-grid').innerHTML = items.map((item) => `<article class="glossary-card"><span>${item.icon}</span><div><h3>${item.term}</h3><b>${item.label}</b><p>${item.detail}</p></div></article>`).join(''); }
function capabilityChip(label, value) { return `<span class="${value === true ? 'on' : ''}">${label}: ${value === true ? 'yes' : unknown(value)}</span>`; }
function showVariant(id) { const model = byId(state.models, 'id', id); if (!model) return; const provider = providerFor(model); const price = pricingFor(model); const capability = capabilityFor(model); const endpoint = endpointFor(model); $('#detail-content').innerHTML = `<div class="detail-title"><span class="provider-logo ${provider.regions.includes('US') ? 'blue' : 'red'}">${provider.name.slice(0, 1)}</span><div><span class="eyebrow">${provider.name} · ${model.modelFamily}</span><h2>${model.modelName}</h2><p>${model.modelType.join(' / ')} · Model ID: ${model.modelId}</p></div></div><div class="positioning">${capability.recommendedUsage?.join(' · ') || 'unknown'}</div><div class="capabilities">${capabilityChip('Reasoning',capability.reasoning)}${capabilityChip('Coding',capability.coding)}${capabilityChip('Vision',capability.vision)}${capabilityChip('Audio',capability.audio)}${capabilityChip('Context',capability.contextLength)}${capabilityChip('Streaming',capability.streaming)}${capabilityChip('Function Calling',capability.functionCalling)}${capabilityChip('JSON Mode',capability.jsonMode)}${capabilityChip('Tool Calling',capability.toolCalling)}</div><div class="detail-grid"><div><h4>推荐用途</h4><ul class="detail-list">${(capability.recommendedUsage || ['unknown']).map((item) => `<li>✓ ${item}</li>`).join('')}</ul><h4>避免用途</h4><p class="muted">${(capability.avoidUsage || ['unknown']).join(' · ')}</p><h4>价格</h4><p class="muted">输入：${unknown(price.inputPrice)} ${price.currency || ''} · 输出：${unknown(price.outputPrice)} ${price.currency || ''}<br>单位：${price.unit || 'unknown'} · 生效时间：${price.effectiveFrom || 'unknown'}</p></div><div class="compare-box"><h4>API 参数</h4><div class="api-fact"><b>Base URL</b><code>${endpoint.baseUrl || 'unknown'}</code></div><div class="api-fact"><b>Compatible Format</b><code>${endpoint.apiCompatibleFormat || 'unknown'}</code></div><div class="api-fact"><b>Authentication</b><code>${endpoint.authentication || 'unknown'}</code></div><h4>数据状态</h4><p class="muted">来源：${model.source || 'unknown'}<br>最后核验：${model.lastVerified || 'unknown'}</p></div></div>`; $('#modal').classList.remove('hidden'); }
function renderRegistryNotice() { const node = document.createElement('p'); node.className = 'registry-notice'; node.textContent = 'Registry 模式：未核验字段显示为 unknown；请在官方来源核实价格和能力后再用于生产决策。'; document.querySelector('#providers').prepend(node); }

document.addEventListener('click', (event) => { const filter = event.target.closest('[data-provider-filter]'); if (filter) { document.querySelectorAll('[data-provider-filter]').forEach((button) => button.classList.remove('active')); filter.classList.add('active'); const value = filter.dataset.providerFilter; $('#provider-grid').innerHTML = state.providers.filter((provider) => value === 'all' || provider.regions.includes(value) || (value === '开源' && provider.focus.includes('open_weights'))).map(providerCard).join(''); } const choice = event.target.closest('[data-recommendation]'); if (choice) { document.querySelectorAll('[data-recommendation]').forEach((button) => button.classList.remove('selected')); choice.classList.add('selected'); state.selectedRecommendation = choice.dataset.recommendation; renderRecommendation(); } const variant = event.target.closest('[data-variant]'); if (variant) showVariant(variant.dataset.variant); });
$('#modal-close').addEventListener('click', () => $('#modal').classList.add('hidden')); $('#modal').addEventListener('click', (event) => { if (event.target.id === 'modal') $('#modal').classList.add('hidden'); }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') $('#modal').classList.add('hidden'); });
loadRegistry().catch((error) => { console.error(error); document.body.insertAdjacentHTML('beforeend', '<p class="load-error">请通过本地静态服务器启动，以加载 Registry JSON 数据。</p>'); });
